name: youtube_main_view
description: "Youtube Main View"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/youtube_main_view

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:
  june:

dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  insta_style_bottom_navi2:
  june_view: #@add
  june_view_more: #@add
  screenutil_module:

flutter:
  assets:
    - assets/view/insta_style_bottom_navi2/
    - assets/view/youtube_main_view/
  uses-material-design: true